/* PROCESS */
export const GET_PROCESSES              = 'GET_PROCESSES';
export const GET_PROCESSES_SUCCESS      = 'GET_PROCESSES_SUCCESS';
export const GET_PROCESSES_FAILED       = 'GET_PROCESSES_FAILED';
export const SELECT_PROCESS             = 'SELECT_PROCESS';
export const ADD_PROCESS                = 'ADD_PROCESS';
export const ADD_PROCESS_SUCCESS        = 'ADD_PROCESS_SUCCESS';
export const ADD_PROCESS_FAILED         = 'ADD_PROCESS_FAILED';
export const UPDATE_PROCESS             = 'UPDATE_PROCESS';
export const UPDATE_PROCESS_SUCCESS     = 'UPDATE_PROCESS_SUCCESS';
export const UPDATE_PROCESS_FAILED      = 'UPDATE_PROCESS_FAILED';
export const DELETE_PROCESS             = 'DELETE_PROCESS';
export const DELETE_PROCESS_SUCCESS     = 'DELETE_PROCESS_SUCCESS';
export const DELETE_PROCESS_FAILED      = 'DELETE_PROCESS_FAILED';

export const START_PROCESS              = 'START_PROCESS';
export const START_PROCESS_SUCCESS      = 'START_PROCESS_SUCCESS';
export const START_PROCESS_FAILED       = 'START_PROCESS_FAILED';
export const STOP_PROCESS               = 'STOP_PROCESS';
export const STOP_PROCESS_SUCCESS       = 'STOP_PROCESS_SUCCESS';
export const STOP_PROCESS_FAILED        = 'STOP_PROCESS_FAILED';
export const SCHEDULE_PROCESS           = 'SCHEDULE_PROCESS';
export const SCHEDULE_PROCESS_SUCCESS   = 'SCHEDULE_PROCESS_SUCCESS';
export const SCHEDULE_PROCESS_FAILED    = 'SCHEDULE_PROCESS_FAILED';
export const GET_PROCESS_RESULT         = 'GET_PROCESS_RESULT';
export const GET_PROCESS_RESULT_SUCCESS = 'GET_PROCESS_RESULT_SUCCESS';
export const GET_PROCESS_RESULT_FAILED  = 'GET_PROCESS_RESULT_FAILED';
